const SET_MAP_DATA = 'SET_MAP_DATA';
const SET_NEW_REGION = 'SET_NEW_REGION';
const EDIT_REGION = 'EDIT_REGION';
const DELETE_REGION = 'DELETE_REGION';
const DEACTIVE_REGION = 'DEACTIVE_REGION';

export { SET_MAP_DATA, SET_NEW_REGION, EDIT_REGION, DELETE_REGION, DEACTIVE_REGION }

